import React, { useState } from 'react';
import { 
  CheckCircle2, 
  XCircle, 
  ShoppingCart, 
  Ban, 
  Sparkles, 
  Check, 
  ShieldCheck, 
  AlertTriangle,
  ArrowRight,
  Share2,
  Copy
} from 'lucide-react';

export default function Recommendations({ recommendations, setActiveTab }) {
  const [shoppingCart, setShoppingCart] = useState([]);
  const [copied, setCopied] = useState(false);
  const buyList = recommendations?.buy || [];
  const dontBuyList = recommendations?.dont_buy || [];

  const getItemEmoji = (name) => {
    const n = (name || '').toLowerCase();
    if (n.includes('milk')) return '🥛';
    if (n.includes('rice')) return '🍚';
    if (n.includes('tomato')) return '🍅';
    if (n.includes('egg')) return '🥚';
    if (n.includes('bread')) return '🍞';
    if (n.includes('potato')) return '🥔';
    if (n.includes('oil')) return '🛢️';
    if (n.includes('paneer') || n.includes('cheese')) return '🧀';
    if (n.includes('spinach') || n.includes('palak')) return '🥬';
    if (n.includes('banana')) return '🍌';
    if (n.includes('chicken') || n.includes('meat')) return '🍗';
    if (n.includes('quinoa') || n.includes('grain')) return '🌾';
    return '📦';
  };

  const handleToggleCart = (itemName) => {
    if (shoppingCart.includes(itemName)) {
      setShoppingCart(shoppingCart.filter(item => item !== itemName));
    } else {
      setShoppingCart([...shoppingCart, itemName]);
    }
  };

  const handleShareWhatsApp = () => {
    const itemsToShare = buyList.map(item => `• ${item.item_name} (${item.suggested_amount}) - ${item.reason}`).join('\n');
    const text = `🛒 *PantryPilot Smart Shopping List:*\n\n${itemsToShare}\n\nGenerated by PantryPilot Assistant`;
    const url = `https://api.whatsapp.com/send?text=${encodeURIComponent(text)}`;
    window.open(url, '_blank');
  };

  const handleCopyList = () => {
    const itemsToShare = buyList.map(item => `• ${item.item_name} (${item.suggested_amount})`).join('\n');
    const text = `🛒 PantryPilot Shopping List:\n\n${itemsToShare}`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center space-x-2">
            <span className="p-2 bg-emerald-100 text-emerald-700 rounded-xl">
              <ShoppingCart className="w-5 h-5" />
            </span>
            <h1 className="text-2xl font-extrabold text-slate-900">Buy / Don't Buy Recommendations</h1>
          </div>
          <p className="text-sm text-slate-500 mt-1">
            Smart decision engine to stop duplicate purchases and ensure you only buy what you need.
          </p>
        </div>

        {/* Action Buttons: WhatsApp & Copy */}
        <div className="flex items-center space-x-2">
          <button
            onClick={handleShareWhatsApp}
            className="inline-flex items-center space-x-1.5 px-3 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs shadow-sm transition-colors"
            title="Share shopping list to WhatsApp"
          >
            <Share2 className="w-3.5 h-3.5" />
            <span>WhatsApp List</span>
          </button>

          <button
            onClick={handleCopyList}
            className="inline-flex items-center space-x-1.5 px-3 py-2 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold text-xs border border-slate-200 transition-colors"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied!' : 'Copy List'}</span>
          </button>
        </div>
      </div>

      {/* Two Column Split: BUY vs DON'T BUY */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* BUY COLUMN */}
        <div className="bg-white rounded-3xl p-6 border-2 border-emerald-500/20 shadow-md flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between pb-4 border-b border-slate-100 mb-4">
              <div className="flex items-center space-x-2">
                <div className="w-8 h-8 rounded-xl bg-emerald-100 text-emerald-700 flex items-center justify-center font-bold">
                  <CheckCircle2 className="w-5 h-5" />
                </div>
                <div>
                  <h2 className="text-lg font-extrabold text-emerald-900">BUY (Needed Soon)</h2>
                  <p className="text-xs text-emerald-600">Items low in stock or near exhaustion</p>
                </div>
              </div>
              <span className="px-3 py-1 rounded-full text-xs font-bold bg-emerald-100 text-emerald-800">
                {buyList.length} Recommended
              </span>
            </div>

            <div className="space-y-4">
              {buyList.length === 0 ? (
                <div className="py-12 text-center text-slate-400">
                  <CheckCircle2 className="w-8 h-8 mx-auto mb-2 text-emerald-500" />
                  <p className="text-sm font-semibold">Your pantry is well stocked!</p>
                  <p className="text-xs">No immediate replenishments needed.</p>
                </div>
              ) : (
                buyList.map((item, idx) => {
                  const isInCart = shoppingCart.includes(item.item_name);
                  return (
                    <div 
                      key={idx} 
                      className="p-4 rounded-2xl bg-emerald-50/40 border border-emerald-100 hover:border-emerald-300 transition-all"
                    >
                      <div className="flex items-center justify-between mb-2">
                        <div className="flex items-center space-x-2">
                          <span className="text-base">{getItemEmoji(item.item_name)}</span>
                          <h3 className="text-sm font-extrabold text-slate-900">{item.item_name}</h3>
                          <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-emerald-200 text-emerald-900">
                            {item.category}
                          </span>
                        </div>
                        <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full uppercase ${
                          item.urgency === 'High' ? 'bg-rose-100 text-rose-700' : 'bg-amber-100 text-amber-700'
                        }`}>
                          {item.urgency || 'Medium'} Urgency
                        </span>
                      </div>

                      {/* Stock vs Suggested */}
                      <div className="flex items-center space-x-4 text-xs text-slate-600 mb-2">
                        <span>Current Stock: <strong>{item.current_stock}</strong></span>
                        <span>•</span>
                        <span>Suggested: <strong className="text-emerald-700">{item.suggested_amount}</strong></span>
                      </div>

                      {/* Short Reason Required */}
                      <p className="text-xs text-slate-700 italic bg-white/70 p-2.5 rounded-xl border border-emerald-100 mb-3">
                        "{item.reason}"
                      </p>

                      <button
                        onClick={() => handleToggleCart(item.item_name)}
                        className={`w-full py-2 rounded-xl text-xs font-bold flex items-center justify-center space-x-1.5 transition-colors ${
                          isInCart
                            ? 'bg-emerald-700 text-white'
                            : 'bg-white hover:bg-emerald-100 text-emerald-800 border border-emerald-300'
                        }`}
                      >
                        {isInCart ? <Check className="w-3.5 h-3.5" /> : <ShoppingCart className="w-3.5 h-3.5" />}
                        <span>{isInCart ? 'Added to Quick List' : 'Add to Shopping List'}</span>
                      </button>
                    </div>
                  );
                })
              )}
            </div>
          </div>
        </div>

        {/* DON'T BUY COLUMN */}
        <div className="bg-white rounded-3xl p-6 border-2 border-rose-500/20 shadow-md flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between pb-4 border-b border-slate-100 mb-4">
              <div className="flex items-center space-x-2">
                <div className="w-8 h-8 rounded-xl bg-rose-100 text-rose-700 flex items-center justify-center font-bold">
                  <Ban className="w-5 h-5" />
                </div>
                <div>
                  <h2 className="text-lg font-extrabold text-rose-900">DON'T BUY (Skip For Now)</h2>
                  <p className="text-xs text-rose-600">Avoid duplicate spending & expiry waste</p>
                </div>
              </div>
              <span className="px-3 py-1 rounded-full text-xs font-bold bg-rose-100 text-rose-800">
                {dontBuyList.length} Avoided
              </span>
            </div>

            <div className="space-y-4">
              {dontBuyList.length === 0 ? (
                <div className="py-12 text-center text-slate-400">
                  <p className="text-sm">No overstock items detected.</p>
                </div>
              ) : (
                dontBuyList.map((item, idx) => (
                  <div 
                    key={idx} 
                    className="p-4 rounded-2xl bg-rose-50/40 border border-rose-100 hover:border-rose-300 transition-all"
                  >
                    <div className="flex items-center justify-between mb-2">
                      <div className="flex items-center space-x-2">
                        <span className="text-base">{getItemEmoji(item.item_name)}</span>
                        <h3 className="text-sm font-extrabold text-slate-900">{item.item_name}</h3>
                        <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-slate-200 text-slate-800">
                          {item.category}
                        </span>
                      </div>
                      <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-rose-200 text-rose-900">
                        {item.risk_factor || 'Overstocked'}
                      </span>
                    </div>

                    <div className="text-xs text-slate-600 mb-2">
                      <span>In Pantry: <strong className="text-slate-900">{item.current_stock}</strong></span>
                    </div>

                    {/* Short Reason Required */}
                    <p className="text-xs text-rose-950 italic bg-white/70 p-2.5 rounded-xl border border-rose-100">
                      "{item.reason}"
                    </p>
                  </div>
                ))
              )}
            </div>
          </div>

          <div className="mt-6 pt-4 border-t border-slate-100 text-xs text-slate-500 flex items-center justify-between">
            <span>Estimated money saved from avoided duplicates:</span>
            <span className="text-sm font-extrabold text-emerald-700">+₹420.00</span>
          </div>
        </div>
      </div>
    </div>
  );
}
